server:
  port: 8881
spring:
  application:
    name: jpademo
    ## ���ݿ�����
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      ##  Hikari ���ӳ����� ------ ��ϸ��������ʣ�https://github.com/brettwooldridge/HikariCP
      #���Բ���   https://blog.csdn.net/qq_32953079/article/details/81502237
      ##��С������������
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
